version: '3.8'
services:
  postgres_taxi:
    image: postgres
    environment:
      POSTGRES_USER: kestra
      POSTGRES_PASSWORD: k3str4
      POSTGRES_DB: postgres-db
    ports:
      - "5434:5432"  # Use 5434 to avoid conflicts with the first file
    networks:
      - shared_networks

  pgadmin:
    image: dpage/pgadmin4
    ports:
      - "5050:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: admin

    networks:
      - shared_networks 

networks:
  shared_networks:
    name: kestra_postgre
    external: true
